FROM node:20-slim
WORKDIR /app

# Instalar dependencias necesarias para compilación de módulos nativos
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/*

# Copiar manifiestos
COPY package*.json ./

# Forzar instalación limpia de dependencias
RUN npm install

EXPOSE 3000

# Next.js dev server
CMD ["npm", "run", "dev"]
