// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Softcoinp.Backend;

#nullable disable

namespace Softcoinp.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328210342_AddUserPermissions")]
    partial class AddUserPermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Softcoinp.Backend.Models.Anotacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PersonalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegistradoPor")
                        .HasColumnType("uuid");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("VehiculoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Anotaciones");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<string>("Entity")
                        .HasColumnType("text");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.Correspondencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("EntregadoPor")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaEntregaLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEntregaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRecepcionLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRecepcionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotaEntrega")
                        .HasColumnType("text");

                    b.Property<string>("NumeroGuia")
                        .HasColumnType("text");

                    b.Property<string>("RecibidoPor")
                        .HasColumnType("text");

                    b.Property<Guid?>("RegistradoPor")
                        .HasColumnType("uuid");

                    b.Property<string>("Remitente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoDocumento")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Correspondencias");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.Personal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaBloqueoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsBloqueado")
                        .HasColumnType("boolean");

                    b.Property<string>("MotivoBloqueo")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.ToTable("Personal");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.Registro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorVehiculo")
                        .HasColumnType("text");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("FotoVehiculoUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("HoraIngresoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HoraSalidaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarcaVehiculo")
                        .HasColumnType("text");

                    b.Property<string>("ModeloVehiculo")
                        .HasColumnType("text");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlacaVehiculo")
                        .HasColumnType("text");

                    b.Property<Guid?>("RegistradoPor")
                        .HasColumnType("uuid");

                    b.Property<string>("TelefonoPersona")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoVehiculo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.RegistroVehiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("FotoVehiculoUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("HoraIngresoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HoraSalidaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Marca")
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .HasColumnType("text");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RegistradoPor")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoVehiculo")
                        .HasColumnType("text");

                    b.Property<Guid?>("VehiculoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehiculoId");

                    b.ToTable("RegistrosVehiculos");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.TipoPersonal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposPersonal");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Activo = true,
                            Nombre = "Empleado"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Activo = true,
                            Nombre = "Visitante"
                        });
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uuid");

                    b.Property<string>("ViewKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId1");

                    b.HasIndex("UserId", "ViewKey")
                        .IsUnique();

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.Vehiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsBloqueado")
                        .HasColumnType("boolean");

                    b.Property<string>("Marca")
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .HasColumnType("text");

                    b.Property<string>("MotivoBloqueo")
                        .HasColumnType("text");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoVehiculo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.Anotacion", b =>
                {
                    b.HasOne("Softcoinp.Backend.Models.Personal", "Personal")
                        .WithMany("Anotaciones")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Softcoinp.Backend.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Personal");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.Registro", b =>
                {
                    b.HasOne("Softcoinp.Backend.Models.Personal", "Personal")
                        .WithMany("Registros")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.RegistroVehiculo", b =>
                {
                    b.HasOne("Softcoinp.Backend.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.UserPermission", b =>
                {
                    b.HasOne("Softcoinp.Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Softcoinp.Backend.Models.User", null)
                        .WithMany("Permissions")
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.Vehiculo", b =>
                {
                    b.HasOne("Softcoinp.Backend.Models.Personal", "Personal")
                        .WithMany()
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.Personal", b =>
                {
                    b.Navigation("Anotaciones");

                    b.Navigation("Registros");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.User", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
