// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Softcoinp.Backend;

#nullable disable

namespace Softcoinp.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Softcoinp.Backend.Models.Anotacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("PersonalId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RegistradoPor")
                        .HasColumnType("char(36)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("VehiculoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Anotaciones");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Data")
                        .HasColumnType("longtext");

                    b.Property<string>("Entity")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("UserAgent")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.Correspondencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("EntregadoPor")
                        .HasColumnType("char(36)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaEntregaLocal")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaEntregaUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRecepcionLocal")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRecepcionUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NotaEntrega")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroGuia")
                        .HasColumnType("longtext");

                    b.Property<string>("RecibidoPor")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("RegistradoPor")
                        .HasColumnType("char(36)");

                    b.Property<string>("Remitente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDocumento")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Correspondencias");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.EntregaRecibo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Apartamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaEntregaUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ReciboPublicoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RegistradoPor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResidenteNombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ReciboPublicoId");

                    b.ToTable("EntregasRecibos");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.Personal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaBloqueoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsBloqueado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MotivoBloqueo")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.ToTable("Personal");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.ReciboPublico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Servicio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalEntregados")
                        .HasColumnType("int");

                    b.Property<int>("TotalRecibidos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RecibosPublicos");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.Registro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ColorVehiculo")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ConductorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ConductorNombre")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ConductorSalidaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ConductorSalidaNombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmailPersona")
                        .HasColumnType("longtext");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("FotoVehiculoUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("HoraIngresoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("HoraSalidaUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MarcaVehiculo")
                        .HasColumnType("longtext");

                    b.Property<string>("ModeloVehiculo")
                        .HasColumnType("longtext");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PlacaVehiculo")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("RegistradoPor")
                        .HasColumnType("char(36)");

                    b.Property<string>("TelefonoPersona")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoVehiculo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConductorId");

                    b.HasIndex("ConductorSalidaId");

                    b.HasIndex("Documento");

                    b.HasIndex("HoraIngresoUtc");

                    b.HasIndex("HoraSalidaUtc");

                    b.HasIndex("PersonalId");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.RegistroVehiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ConductorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ConductorNombre")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ConductorSalidaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ConductorSalidaNombre")
                        .HasColumnType("longtext");

                    b.Property<string>("FotoVehiculoUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("HoraIngresoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("HoraSalidaUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Marca")
                        .HasColumnType("longtext");

                    b.Property<string>("Modelo")
                        .HasColumnType("longtext");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("RegistradoPor")
                        .HasColumnType("char(36)");

                    b.Property<string>("TipoVehiculo")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("VehiculoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ConductorId");

                    b.HasIndex("ConductorSalidaId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("RegistrosVehiculos");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Key");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.TipoPersonal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposPersonal");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Activo = true,
                            Nombre = "Empleado"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Activo = true,
                            Nombre = "Visitante"
                        });
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RefreshTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("char(36)");

                    b.Property<string>("ViewKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId1");

                    b.HasIndex("UserId", "ViewKey")
                        .IsUnique();

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.Vehiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsBloqueado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Marca")
                        .HasColumnType("longtext");

                    b.Property<string>("Modelo")
                        .HasColumnType("longtext");

                    b.Property<string>("MotivoBloqueo")
                        .HasColumnType("longtext");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoVehiculo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.Anotacion", b =>
                {
                    b.HasOne("Softcoinp.Backend.Models.Personal", "Personal")
                        .WithMany("Anotaciones")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Softcoinp.Backend.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Personal");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.EntregaRecibo", b =>
                {
                    b.HasOne("Softcoinp.Backend.Models.ReciboPublico", "ReciboPublico")
                        .WithMany("Entregas")
                        .HasForeignKey("ReciboPublicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReciboPublico");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.Registro", b =>
                {
                    b.HasOne("Softcoinp.Backend.Models.Personal", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Softcoinp.Backend.Models.Personal", "ConductorSalida")
                        .WithMany()
                        .HasForeignKey("ConductorSalidaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Softcoinp.Backend.Models.Personal", "Personal")
                        .WithMany("Registros")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conductor");

                    b.Navigation("ConductorSalida");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.RegistroVehiculo", b =>
                {
                    b.HasOne("Softcoinp.Backend.Models.Personal", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Softcoinp.Backend.Models.Personal", "ConductorSalida")
                        .WithMany()
                        .HasForeignKey("ConductorSalidaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Softcoinp.Backend.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId");

                    b.Navigation("Conductor");

                    b.Navigation("ConductorSalida");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.UserPermission", b =>
                {
                    b.HasOne("Softcoinp.Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Softcoinp.Backend.Models.User", null)
                        .WithMany("Permissions")
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.Vehiculo", b =>
                {
                    b.HasOne("Softcoinp.Backend.Models.Personal", "Personal")
                        .WithMany("Vehiculos")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.Personal", b =>
                {
                    b.Navigation("Anotaciones");

                    b.Navigation("Registros");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.ReciboPublico", b =>
                {
                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("Softcoinp.Backend.Models.User", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
